### ISSUE TITLE
(URGENT) UnitsML expressions fail to validate

### ISSUE THREAD

**Issue by opoudjis** [plurimath/plurimath#236]
Several UnitsML expressions in bipm-si-brochure have ceased validating under Plurimath since at least version 0.7.0. I can not go further back than 0.7.0, because I cannot install ruby-xslt locally.

This is the list of expressions:

````
"unitsml(cd*sr*kg^(-1)*m^(-2)*s^3)"
"unitsml(F)" = "unitsml(kg^(-1)*m^(-2)*s^4*A^2)"
"unitsml(Gy)" = "unitsml(m^2*s^(-2))"
"unitsml(H)" = "unitsml(kg*m^2*s^(-2)*A^(-2))"
"unitsml(J)" = "unitsml(kg*m^2*s^(-2))"
"unitsml(J)" = "unitsml(m^2*kg*s^(-2))"
"unitsml(J*K^(-1)*kg^(-1))"
"unitsml(J*K^(-1)*mol^(-1))"
"unitsml(kg*m^(-1)*s^(-1))"
"unitsml(kg*m^(-1)*s^(-2))"
"unitsml(kg*m^(-2)*s^(-1))"
"unitsml(kg*m^2*s^(-1))"
"unitsml(kg*m^2*s^(-2))"
"unitsml(kg*m^2*s^(-2)*K^(-1))"
"unitsml(kg*m^2*s^(-2)*mol^(-1))"
"unitsml(kg*m^2*s^(-2)*mol^(-1)*K^(-1))"
"unitsml(kg*m^2*s^(-3))"
"unitsml(kg^(-1)*m^(-3)*s^4*A^2)"
"unitsml(lm)" = "unitsml(cd*m^2*m^(-2))" = "unitsml(cd*sr)"
"unitsml(m^(-2)*kg^(-1)*s^3*cd*sr)"
"unitsml(m^2*kg*s^(-1))"
"unitsml(m^2*kg*s^(-2)*K^(-1))"
"unitsml(m^2*s^(-2))"
"unitsml(m^2*s^(-2)*K^(-1))"
"unitsml(m^2*s^(-3))"
"unitsml(m^2//s)"
"unitsml(m^3*kg^(-1))"
"unitsml(mol*s^(-1)*m^(-3))"
"unitsml(N*s//m^2,symbol:N cdot s//m^2)"
"unitsml(Ohm)" = "unitsml(kg*m^2*s^(-3)*A^(-2))"
"unitsml(Pa)" = "unitsml(kg*m^(-1)*s^(-2))"
"unitsml(S)" = "unitsml(kg^(-1)*m^(-2)*s^3*A^2)"
"unitsml(sr)" = "unitsml(m^2/m^2)"
"unitsml(Sv)" = "unitsml(m^2*s^(-2))"
"unitsml(V)" = "unitsml(kg*m^2*s^(-3)*A^(-1))"
"unitsml(W)" = "unitsml(kg*m^2*s^(-3))"
"unitsml(W)" = "unitsml(m^2*kg*s^(-3))"
"unitsml(W*sr^(-1)*m^(-2))"
"unitsml(Wb)" = "unitsml(kg*m^2*s^(-2)*A^(-1))"
1 "unitsml(cd)" = (ii(K)_("cd")/683) "unitsml(kg*m^2*s^(-3)*sr^(-1))"
1 "unitsml(K)" = ((1.380649 xx 10^(-23))/k) "unitsml(kg*m^2*s^(-2))"
1 "unitsml(kg)" = (h/(6.62607015 xx 10^(-34))) "unitsml(m^(-2)*s)"
h = 6.62607015 xx 10^(−34) "unitsml(kg*m^2*s^(-1))"
ii(K)_("cd") = 683 "unitsml(cd*sr*kg^(-1)*m^(-2)*s^3)"
k = 1.380649 xx 10^(−23) "unitsml(kg*m^2*s^(-2)*K^(-1))"
````

So for example, 

````
 Plurimath::Math.parse('"unitsml(kg*m^2)"', "asciimath")
````

parses correctly—including recognising unitsml() as an expression:

````
#<Plurimath::Math::Formula:0x0000000107ccca88
 @displaystyle=true,
 @input_string="\"unitsml(kg*m^2)\"",
 @left_right_wrapper=true,
 @unitsml=true,
 @value=
  [#<Plurimath::Math::Function::FontStyle::Normal:0x0000000107040eb8 @parameter_one=#<Plurimath::Math::Symbol:0x0000000107ccd258 @value="kg">, @parameter_two="normal">,
   #<Plurimath::Math::Symbol:0x0000000107cccf88 @value="&#x22c5;">,
   #<Plurimath::Math::Function::Power:0x00000001070ae5d0
    @parameter_one=#<Plurimath::Math::Function::FontStyle::Normal:0x00000001070c8598 @parameter_one=#<Plurimath::Math::Symbol:0x0000000107cccd08 @value="m">, @parameter_two="normal">,
    @parameter_two=#<Plurimath::Math::Number:0x00000001070c09d8 @value="2">>]>
````

Whereas without the quotes, unitsml() is not recognised

````
irb(main):007> Plurimath::Math.parse('unitsml(kg*m^2)', "asciimath")
=> 
#<Plurimath::Math::Formula:0x0000000105ef3110
 @displaystyle=true,
 @input_string="unitsml(kg*m^2)",
 @left_right_wrapper=true,
 @value=
  [#<Plurimath::Math::Symbol:0x0000000105efd7f0 @value="u">,
   #<Plurimath::Math::Symbol:0x0000000105efd160 @value="n">,
   #<Plurimath::Math::Symbol:0x0000000105efd070 @value="i">,
   #<Plurimath::Math::Symbol:0x0000000105efb770 @value="t">,
   #<Plurimath::Math::Symbol:0x0000000105efb6d0 @value="s">,
   #<Plurimath::Math::Symbol:0x0000000105ef8de0 @value="m">,
   #<Plurimath::Math::Symbol:0x0000000105ef8d40 @value="l">,
   #<Plurimath::Math::Function::Fenced:0x0000000105ef51e0
    @options={},
    @parameter_one=#<Plurimath::Math::Symbol:0x0000000105ef5be0 @value="(">,
    @parameter_three=#<Plurimath::Math::Symbol:0x0000000105ef5280 @value=")">,
    @parameter_two=
     [#<Plurimath::Math::Symbol:0x0000000105ef85c0 @value="k">,
      #<Plurimath::Math::Symbol:0x0000000105ef6810 @value="g">,
      #<Plurimath::Math::Symbol:0x0000000105ef6770 @value="&#x22c5;">,
      #<Plurimath::Math::Function::Power:0x00000001078a6850
       @parameter_one=#<Plurimath::Math::Symbol:0x0000000105ef62c0 @value="m">,
       @parameter_two=#<Plurimath::Math::Number:0x00000001078a8fd8 @value="2">>]>]>
````

However, more complex expressions are failing:

````
irb(main):008> Plurimath::Math.parse('"unitsml(kg*m^2*s^(-2))"', "asciimath")
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/plurimath-0.8.0/lib/plurimath/math.rb:69:in `parse_error!': [plurimath] Error: Failed to parse the following formula with type `asciimath`. (Plurimath::Math::ParseError)
[plurimath] Please first manually validate the formula.
[plurimath] If this is a bug, please report the formula at our issue tracker at:
[plurimath] https://github.com/plurimath/plurimath/issues
---- FORMULA BEGIN ----
"unitsml(kg*m^2*s^(-2))"
---- FORMULA END ----

	from /Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/plurimath-0.8.0/lib/plurimath/math.rb:49:in `rescue in parse'
	from /Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/plurimath-0.8.0/lib/plurimath/math.rb:43:in `parse'
	from (irb):8:in `<main>'
	from /Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/irb-1.12.0/exe/irb:9:in `<top (required)>'
	from /Users/nickn/.rbenv/versions/3.2.3/bin/irb:25:in `load'
	from /Users/nickn/.rbenv/versions/3.2.3/bin/irb:25:in `<main>'
````

**Comment by ronaldtse** [comment]
@suleman-uzair can you please help fix this ASAP? Thanks.

**Comment by suleman-uzair** [comment]
> Whereas without the quotes, unitsml() is not recognised

@opoudjis That’s right. We currently don’t recognize without quotes as we are following the syntax explained [here](https://github.com/plurimath/plurimath/issues/33#:~:text=The%20AsciiMath%20string,to%20process%20it.).
However, if we want to change that behavior we can do that as well ?

Secondly, the crashing issue is fixed in the [PR# UnitsML expressions validations](https://github.com/plurimath/plurimath/pull/237).

**Comment by opoudjis** [comment]
No need to change behaviour. Confirming fix.

**Comment by opoudjis** [comment]
Confirmed.

**Comment by opoudjis** [comment]
Well, release fix after you've also done the change requested in https://github.com/plurimath/plurimath/issues/222
