### ISSUE TITLE
Plurimath gem not useable due to error in require statements

### ISSUE THREAD

**Issue by opoudjis** [plurimath/plurimath#54]
Confirmed with latest version

irb:

`require "plurimath"`

result:

````
/Users/nickn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/plurimath-0.2.0/lib/plurimath/math/function.rb:2:in `require_relative': cannot load such file -- /Users/nickn/env/versions/3.1.2/lib/ruby/gems/3.1.0/gems/plurimath-0.2.0/lib/plurimath/math/function/abs (LoadError)
        from /Users/nickn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/plurimath-0.2.0/lib/plurimath/math/function.rb:2:in `block in <top (required)>'
        from /Users/nickn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/plurimath-0.2.0/lib/plurimath/math/function.rb:1:in `each'
        from /Users/nickn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/plurimath-0.2.0/lib/plurimath/math/function.rb:1:in `<top (required)>'
        from /Users/nickn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/plurimath-0.2.0/lib/plurimath/math.rb:12:in `require_relative'
        from /Users/nickn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/plurimath-0.2.0/lib/plurimath/math.rb:12:in `<top (required)>'
        from /Users/nickn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/plurimath-0.2.0/lib/plurimath.rb:4:in `require_relative'
        from /Users/nickn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/plurimath-0.2.0/lib/plurimath.rb:4:in `<top (required)>'
        from <internal:/Users/nickn/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
        from <internal:/Users/nickn/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
        from <internal:/Users/nickn/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from (irb):1:in `<main>'                                           
        from /Users/nickn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
        from /Users/nickn/.rbenv/versions/3.1.2/bin/irb:25:in `load'       
	from /Users/nickn/.rbenv/versions/3.1.2/bin/irb:25:in `<main>'
<internal:/Users/nickn/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- plurimath (LoadError)
	from <internal:/Users/nickn/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from (irb):1:in `<main>'
	from /Users/nickn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
	from /Users/nickn/.rbenv/versions/3.1.2/bin/irb:25:in `load'
	from /Users/nickn/.rbenv/versions/3.1.2/bin/irb:25:in `<main>'
````

I note that the failing line has:

````
Dir[File.join(__dir__, "function/**/*.rb")].each do |file|
  require_relative file.gsub(".rb", "")
end
````

`require_relative` requires a relative path. Either:

````
Dir["function/**/*.rb"].each do |file|
  require_relative file.gsub(".rb", "")
end
````

or

````
Dir[File.join(__dir__, "function/**/*.rb")].each do |file|
  require file.gsub(".rb", "")
end
````

Please rectify this and release the update gem.

**Comment by ronaldtse** [comment]
@suleman-uzair please help address this ASAP, the gem right now cannot be used. Thanks.

**Comment by suleman-uzair** [comment]
> @suleman-uzair please help address this ASAP, the gem right now cannot be used. Thanks.

Sure @ronaldtse , I'm working on it.

**Comment by suleman-uzair** [comment]
@ronaldtse 

I have been trying to reproduce the issue locally for different ruby versions, following the flow you can see in the video but I was unable to reproduce it on my machine.
Can you share the steps that cause the error?

https://user-images.githubusercontent.com/96812483/193557616-7b5732af-8dd8-43a3-bb80-5821fa899723.mp4

**Comment by ronaldtse** [comment]
@opoudjis @suleman-uzair I was able to do this:

```
irb(main):001:0> require 'plurimath'
=> true
irb(main):002:0> asciimath = "sin(1)"
irb(main):003:0> formula = Plurimath::Math.parse(asciimath, 'asciimath')
=> 
#<Plurimath::Math::Formula:0x00000001087f3588                                                
...
```

I'm also on Ruby 3.1. Not sure why @opoudjis is getting the issue?

**Comment by opoudjis** [comment]
I gave the steps above. I also uninstalled and reinstalled plurimath. I get an abort the minute I do "require plurimath", and I have given the error log above.

The error goes away, as I said, when I do this:

````
Dir[File.join(__dir__, "function/*.rb")].each do |file|
  require_relative file # file.gsub(".rb", "")
end
````

And given that `require_relative` takes a relative and not an absolute file address, I would strongly recommend just changing it.

Bear in mind that you can just do `require_all("function")` instead of the foregoing.

rbenv, version 3.1.2, OSX.

**Comment by ronaldtse** [comment]
I agree with @opoudjis , please change require_relative to take a relative path. That is the correct solution.

However `require_all` is from a third-party gem, not core Ruby functionality.
