### ISSUE TITLE
Plurimath sample code in README does not work

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath#55]
```ruby
asciimath = "sin(1)"
formula = Plurimath::Math.parse(asciimath, :asciimath)
gems/3.1.0/gems/plurimath-0.2.0/lib/plurimath/math.rb:40:in `raise_error!': Type is not valid, please enter string or symbol (Plurimath::Math::Error)                                                       
        from gems/3.1.0/gems/plurimath-0.2.0/lib/plurimath/math.rb:31:in `parse'
        from (irb):3:in `<main>'                                                             
        from gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
```

The problem is instead of `:asciimath` as the type argument, it expects a string `'asciimath'`.

We should support both, i.e. symbol or string. Please also add a corresponding test for this.

**Comment by suleman-uzair** [comment]
Hi @ronaldtse 
Just released a new version of the gem, which will fix the issue.
You can confirm the changes now!

**Comment by suleman-uzair** [comment]
Fixed in https://github.com/plurimath/plurimath/pull/53
