### ISSUE TITLE
regression from latexmath, crashes on normal latex input

### ISSUE THREAD

**Issue by infinity0** [plurimath/plurimath#84]
plurimath can't parse the following, but latexmath can:

```ruby
require 'plurimath'
require 'latexmath'

latex = "$$   (\mathcal{F}f)(y)
    = \frac{1}{\sqrt{2\pi}^{\ n}}
      \int_{\mathbb{R}^n} f(x)\,
      e^{-\mathrm{i} y \cdot x} \,\mathrm{d} x.
$$"

puts Latexmath.parse(latex).to_mathml
puts Plurimath::Math.parse(latex, "latex").to_mathml
```

~~~~
$ ruby test.rb 
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow> [.. etc, output from latexmath is fine ..]
~/.local/share/gem/ruby/3.0.0/gems/parslet-2.0.0/lib/parslet/cause.rb:70:in `raise': Expected one of [ITERATION EXPRESSION, ITERATION] at line 1 char 1. (Parslet::ParseFailed)
	from ~/.local/share/gem/ruby/3.0.0/gems/parslet-2.0.0/lib/parslet/atoms/base.rb:49:in `parse'
	from ~/.local/share/gem/ruby/3.0.0/gems/plurimath-0.2.1/lib/plurimath/latex/parser.rb:16:in `parse'
	from ~/.local/share/gem/ruby/3.0.0/gems/plurimath-0.2.1/lib/plurimath/latex.rb:12:in `to_formula'
	from ~/.local/share/gem/ruby/3.0.0/gems/plurimath-0.2.1/lib/plurimath/math.rb:39:in `parse'
	from test.rb:11:in `<main>'
exit code 1
~~~~

**Comment by infinity0** [comment]
I am using plurimath 0.2.1 and latexmath 0.1.5 from rubygems.

**Comment by ronaldtse** [comment]
Thank you @infinity0 for reporting this. @suleman-uzair would you be able to deal with this during the weekend?
