### ISSUE TITLE
Conversion to Asciimath crashing on undefined map for fine space

### ISSUE THREAD

**Issue by opoudjis** [plurimath/plurimath#89]
From parsing the first document in bipm-si-brochure, https://github.com/metanorma/bipm-si-brochure/blob/main/sources/rec-values/mep-wgfs-nm237-115In_1267THz.adoc

Asciimath original: `f ~~ 1267 "unitsml(THz)"]`

````

math = "<math><mi>f</mi><mo>≈</mo><mn>1267</mn><mo rspace=\"thickmathspace\">⁢</mo><mrow xref=\"U_THz\"><mi mathvariant=\"normal\">THz</mi></mrow></math>"

Plurimath::Math.parse(math, "mathml").to_asciimath
````

which parses as

````
@value=
  [#<Plurimath::Math::Function::F:0x000000011e535498 @parameter_one=nil>,
   #<Plurimath::Math::Symbol:0x000000011e52d928 @value="~~">,
   #<Plurimath::Math::Symbol:0x000000011e526038 @value="1267">,
   {:mo=>{:attributes=>{:rspace=>"thickmathspace"}, :value=>["⁢"]}},
   #<Plurimath::Math::Formula:0x000000011e50eeb0
    @value=[#<Plurimath::Math::Symbol:0x000000011e514c20 @value="THz">],
    @wrapped=false>],
````

 crashes with:

````
eval error: undefined method `to_asciimath' for {:mo=>{:attributes=>{:rspace=>"thickmathspace"}, :value=>["⁢"]}}:Hash

          value.map(&:to_asciimath).join
               ^^^^
  /Users/nickn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/plurimath-0.2.1/lib/plurimath/math/formula.rb:21:in `map'
  /Users/nickn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/plurimath-0.2.1/lib/plurimath/math/formula.rb:21:in `to_asciimath'
````

It is imperative that all Plurimath conversions degrade gracefully; otherwise, they simply cannot be used. 

In this instance, for example, MathML has injected into the expression a fine space, and Asciimath may not have an exact equivalent; if not, it needs to fall back to a generic space.

**Comment by opoudjis** [comment]
Similar error in mn-samples-bipm:

````
<stem type="MathML">
  <math xmlns="http://www.w3.org/1998/Math/MathML">
    <msub>
      <mrow>
        <mstyle mathvariant="italic">
          <mi>D</mi>
        </mstyle>
      </mrow>
      <mrow>
        <mi>i</mi>
      </mrow>
    </msub>
    <mo>=</mo>
    <msub>
      <mrow>
        <mi>x</mi>
      </mrow>
      <mrow>
        <mi>i</mi>
      </mrow>
    </msub>
    <mo>−</mo>
    <msub>
      <mrow>
        <mi>x</mi>
      </mrow>
      <mrow>
        <mrow>
          <mi mathvariant="normal">S</mi>
          <mi mathvariant="normal">R</mi>
          <mi mathvariant="normal">P</mi>
          <mn>27</mn>
        </mrow>
      </mrow>
    </msub>
  </math>
  <asciimath>ii(D)_i = x_i - x_(SRP27)</asciimath>
</stem>
undefined method `to_asciimath' for {:msub=>[{:mrow=>[[#<Plurimath::Math::Symbol:0x0000000126fbc2d8 @value="D">]]}, #<Plurimath::Math::Formula:0x0000000126f2cfe8 @value=[#<Plurimath::Math::Symbol:0x0000000126f3c600 @value="i">], @wrapped=false>]}:Hash

          value.map(&:to_asciimath).join
               ^^^^
````

**Comment by opoudjis** [comment]
And don't know what's happening here:

````
Failure to convert MathML to AsciiMath
<stem type="MathML">
  <math xmlns="http://www.w3.org/1998/Math/MathML">
    <mstyle mathcolor="#ff0000">
      <mtext>Assigned value</mtext>
    </mstyle>
  </math>
  <asciimath>color(red)("Assigned value")</asciimath>
</stem>
undefined method `parameter_one' for "#ff0000":String

          first_value  = parameter_one.parameter_one if parameter_one
                                      ^^^^^^^^^^^^^^
````

**Comment by opoudjis** [comment]
If we're converting MathML to Asciimath in Metanorma, it's as a fallback --- we treat MathML as the authoritative format. If there isn't an Asciimath equivalent of MathML formatting (and there usually is), just skip the feature, but a rendering must be generated.

In the error instances being reported above, I'm preserving the source Asciimath in the XML. So in the immediately foregoing instance, asciidoctor/asciimath (which I'm still using) has correctly converted `color(red)("Assigned value")` into `<math xmlns="http://www.w3.org/1998/Math/MathML"><mstyle mathcolor="#ff0000"><mtext>Assigned value</mtext></mstyle></math>`. The roundtrip to Asciimath is failing with an error.

In reality, if I retain asciimath in the original, I have no need to roundtrip at all. I am doing the roundtripping currently, for debugging.

The only functionality I am currently testing in Plurimath is MathML validation (which now appears to be OK), and MathML > Asciimath conversion; I have not currently started testing Asciimath > MathML conversion, and I'm going to leave that until the MathML validation and MathML > Asciimath conversion settle down.

**Comment by opoudjis** [comment]
I am going to send you in Skype the output of just mn-samples-bipm. The error logs for each document (`document.err`) contain all the errors in converting MathML to Asciimath. I am assuming they fall into a few recurring classes.
